analyzer:
  exclude:
    - lib/generated/i18n.dart
    - lib/**.g.dart
    - lib/**.chopper.dart
  errors:
      todo: warning

linter:
  rules:
      prefer_single_quotes: true
      avoid_classes_with_only_static_members: false