targets: 
  $default:   
    sources:  
    - lib/**
    - swaggers/**  
    - $package$  
    builders: 
      swagger_dart_code_generator:     
        options:           
          input_folder: 'swaggers/'   
          output_folder: 'lib/data/swagger_generated_code/'
          with_base_url: false
          use_default_null_for_lists: false
          build_only_models: false
          default_values_map:
            - type_name: String
              default_value: ""
            - type_name: bool
              default_value: "false"