export 'actor_model.dart';
export 'image_model.dart';
export 'list_movie_model.dart';
export 'movie_model.dart';
export 'result_search_list_model.dart';
export 'search_result_model.dart';
export 'similar_movie_model.dart';
export 'title_model.dart';
export 'trailer_model.dart';
